Feature/dockstore layer only
cancerit/dockstore-cgpmap pull request #22
Opened 2019-11-28 09:38 UTC by keiranmraine

Minimise the places we have installation code, will be more difficult for wxs/wgs container but this was trivial.

2020-09-29 13:00 UTC, byb121 requested changes

2020-09-29 13:04 UTC, keiranmraine commented on scripts/ds-cgpmap.pl
> +1000 has been tested with older versions of HTSlib and found to be a good trade off, comparible speed 1% increase in file size.
? 10000 is the default for htslib, but has an impact on downstream tools.  I've indicated >1000 (which is probably better than +1000) as 1k is a safe trade off that we have tested.

2020-09-29 13:04 UTC, keiranmraine commented on cwls/cgpmap-bamBaiOut.cwl
> +    doc: "Number of CPUs to use where possible"
I don't like coding around bugs.  Not sure why this stops us releasing.

2020-09-29 13:04 UTC, keiranmraine commented on scripts/ds-cgpmap.pl
> +    -threads     -t    Number of threads to use. [1]
Good spot

2020-09-30 10:03 UTC, keiranmraine commented on cwls/cgpmap-bamBaiOut.cwl
> +    doc: "Number of CPUs to use where possible"
On reflection decided that updating doc and minor change in perl script were worthwhile to cover all bases.

All CLW changed:

```cwl
-    doc: "Number of CPUs to use where possible"
+    doc: "Number of CPUs to use where possible - 0/null/not defined to query host for max"
```

All json changes:

```json
-  "threads": null,
+  "threads": 0,
```

Script change:

```perl
-printf $FH "CPU=%d\n", $opts{'t'} if(defined $opts{'t'});
+printf $FH "CPU=%d\n", $opts{'t'} if(defined $opts{'t'} && $opts{'t'} != 0);
```

2020-09-30 10:07 UTC, byb121 approved these changes

2020-09-30 10:08 UTC, merged